### ISSUE TITLE
Unable to Compile Project Due to Missing GLFW Development Libraries on School Computers

### ISSUE THREAD

**Issue by Neroued** [didiersmets/MU5MAM30#1]
We are unable to use the “sudo apt install libglfw3-dev” command on the school computers, which prevents us from compiling and running the project. Would it be possible to add GLFW directly to the repository, perhaps in a branch like “branch_with_glfw”? This might allow us to work on the project without needing to install GLFW manually (though I'm not certain if this will work; I will verify it on Friday).

**Comment by didiersmets** [comment]
Thanks, it should work out of the box now. I tend to put all 3rd party code into an "extern" directory.
